In [1]:
!pip install tensorflow tensorflow-gpu pandas matplotlib sklearn

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for tensorflow-gpu
Failed to build tensorflow-gpu
  Running setup.py install for tensorflow-gpu: started
  Running setup.py install for tensorflow-gpu: finished with status 'error'


  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [18 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\KIIT\AppData\Local\Temp\pip-install-7db6a7mc\tensorflow-gpu_78ae2c23997d47cfa266d46206318b8f\setup.py", line 37, in <module>
      raise Exception(TF_REMOVAL_WARNING)
  Exception:
  
  The "tensorflow-gpu" package has been removed!
  
  Please install "tensorflow" instead.
  
  Other than the name, the two packages have been identical
  since TensorFlow 2.1, or roughly since Sep 2019. For more
  information, see: pypi.org/project/tensorflow-gpu
  
  
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorflow-gpu
  error: subprocess-exited-with-error
  
  Running setup.py install for tensorflow-gpu did not 

In [2]:
import os
import pandas as pd
import numpy as np
import tensorflow as tf

In [3]:
os.path.join('sample_submission.csv','test.csv','train.csv')

'sample_submission.csv\\test.csv\\train.csv'

In [4]:
df=pd.read_csv('train.csv')

In [5]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [6]:
df[df['toxic']==1].head()

id                                       comment_text  \
6   0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   
12  0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......   
16  0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...   
42  001810bf8c45bf5f  You are gay or antisemmitian? \n\nArchangel WH...   
43  00190820581d90ce           FUCK YOUR FILTHY MOTHER IN THE ASS, DRY!   

    toxic  severe_toxic  obscene  threat  insult  identity_hate  
6       1             1        1       0       1              0  
12      1             0        0       0       0              0  
16      1             0        0       0       0              0  
42      1             0        1       0       1              1  
43      1             0        1       0       1              0

In [7]:
df.tail()

id                                       comment_text  \
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [8]:
df.iloc[6]['comment_text']

'COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK'

In [9]:
df[df.columns[2:]].iloc[6]

toxic            1
severe_toxic     1
obscene          1
threat           0
insult           1
identity_hate    0
Name: 6, dtype: int64

# PreProcess

In [21]:
!pip list

Package                       Version
----------------------------- --------------------
absl-py                       1.4.0
alabaster                     0.7.12
anaconda-client               1.11.0
anaconda-navigator            2.3.1
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.11.7
astropy                       5.1
astunparse                    1.6.3
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
bi

In [22]:
from tensorflow.keras.layers import TextVectorization

In [26]:
x=df['comment_text']
y=df[df.columns[2:]].values

In [34]:
Max_FEATURES=200000

In [37]:
vectorizer=TextVectorization(max_tokens=Max_FEATURES,
                            output_sequence_length=1800,
                             output_mode='int')

In [38]:
vectorizer.adapt(x.values)

In [35]:
df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [36]:
df.comment_text

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [25]:
vectorizer.get_vocabulary()

['', '[UNK]']

In [39]:
vectorized_text=vectorizer(x.values)

In [40]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [41]:
dataset=tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset.cache()
dataset=dataset.shuffle(160000)
dataset=dataset.batch(16)
dataset=dataset.prefetch(8)

In [43]:
batch_x,batch_y=dataset.as_numpy_iterator().next()

In [47]:
batch_x.shape

(16, 1800)

In [49]:
len(dataset)

9974

In [48]:
train=dataset.take(int(len(dataset)*.7))
val=dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test=dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [51]:
train_generator=train.as_numpy_iterator()

In [52]:
train_generator.next()

(array([[  16,    2,   63, ...,    0,    0,    0],
        [  12,    9,    6, ...,    0,    0,    0],
        [  48, 3868,   93, ...,    0,    0,    0],
        ...,
        [1083,  635,  830, ...,    0,    0,    0],
        [   2, 1470,    4, ...,    0,    0,    0],
        [   8,   33,   15, ...,    0,    0,    0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

# Creat sequential model 

In [104]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout,Bidirectional, Dense, Embedding

In [106]:
model=Sequential()
model.add(Embedding(Max_FEATURES+1,32))
model.add(Bidirectional(LSTM(32,activation='tanh')))
model.add(Dense(128,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(6,activation='sigmoid'))

# Make Predictions

In [107]:
#

In [108]:
batch=test.as_numpy_iterator().next()

In [109]:
input_text=vectorizer('You freaking suck')

In [110]:
input_text

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([   7, 7158,  397, ...,    0,    0,    0], dtype=int64)>

In [111]:
np.expand_dims(input_text,0)

array([[   7, 7158,  397, ...,    0,    0,    0]], dtype=int64)

In [112]:
model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 2s 2s/step


array([[0.499049  , 0.5002433 , 0.49894914, 0.5004589 , 0.49897188,
        0.49847704]], dtype=float32)

In [113]:
res=model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 0s 215ms/step


In [114]:
np.expand_dims(input_text,0)

array([[   7, 7158,  397, ...,    0,    0,    0]], dtype=int64)

In [115]:
model.predict(np.array([input_text]))

1/1 [==============================] - 0s 215ms/step


array([[0.499049  , 0.5002433 , 0.49894914, 0.5004589 , 0.49897188,
        0.49847704]], dtype=float32)

In [116]:
res=model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 0s 225ms/step


In [117]:
res.shape

(1, 6)

# Evaluate Model

In [118]:
from tensorflow.keras.metrics import Precision,Recall,CategoricalAccuracy

In [119]:
pre=Precision()
re=Recall()
acc=CategoricalAccuracy()

In [120]:
for batch in test.as_numpy_iterator():
    x_true,y_true=batch
    
    yhat=model.predict(x_true)
    
    y_true=y_true.flatten()
    yhat=yhat.flatten()
    
    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)
       

1/1 [==============================] - 0s 361ms/step


1/1 [==============================] - 0s 331ms/step


1/1 [==============================] - 0s 324ms/step


1/1 [==============================] - 0s 378ms/step


1/1 [==============================] - 0s 369ms/step


1/1 [==============================] - 0s 338ms/step


1/1 [==============================] - 0s 357ms/step


In [121]:
print(f'Precision:{pre.result().numpy()},  Recall:{re.result().numpy()},  Accuracy:{acc.result().numpy()}')

Precision:0.031241493299603462,  Recall:0.29497429728507996,  Accuracy:0.0


In [97]:
pip install gradio jinja2

Note: you may need to restart the kernel to use updated packages.


In [103]:
# import gradio as gr